### ISSUE TITLE
How to Run If Not Using Env?

### ISSUE THREAD

**Issue by windowshopr** [singlearity-sports/singlearity-python#2]
Can't wait to get my trial API key. Quick question, running this from Windows 10, Python 3.9, I see in the example to use `env SINGLEARITY_API_KEY=YOUR_API_KEY python pa_pred_very_simple.py` to provide the API key, but what if we're not using a virtual environment? How can we provide our API key to run the script?

Thanks!

**Comment by jsilverpa** [comment]
It is not required to use a virtual environment.   The API KEY uses makes use of the OS environment which is different than a virtual environment.   Here's a [link](https://phoenixnap.com/kb/windows-set-environment-variable) that describes how environment variables work on Windows and how you can set them.

To test if you are setting the environment variable correctly, you can run:

```
import os
print(os.environ.get('SINGLEARITY_API_KEY'))
```

It should print out your API KEY if you've set it correctly.

**Comment by windowshopr** [comment]
Thank you for the detailed answer! I got it working by just using:

```
import os
os.environ['SINGLEARITY_API_KEY'] = "MY_API_KEY_HERE"
```

Made my first API call tonight! Yay! Thanks!
